### ISSUE TITLE
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[5655,10240,32]

### ISSUE THREAD

**Issue by NiuYingchun** [PointCloudYC/SQN_tensorflow#1]
First,thank you for the code.
I use weak_label_ratio 0.01,  When I run main_S3DIS_sqn.py ，this error occurs.But weak_label_ration 0.001, everything is OK.

![image](https://user-images.githubusercontent.com/17853144/165312061-bd0d3bd7-c0fd-4d38-b24f-826677bfe181.png)

**Comment by PointCloudYC** [comment]
Thanks for your attention. When setting the weak ratio to a larger value (e.g., 0.1), the program will suffer GPU OOM due to the custom CUDA trilinear operations. When setting a smaller ratio, say 0.001, the code can work.

**Comment by NiuYingchun** [comment]
Thank you for your reply. Have you tried it on other datasets? Like Scannet or Semantic3D
