### ISSUE TITLE
Any pytorch version

### ISSUE THREAD

**Issue by liuxuexun** [PointCloudYC/SQN_tensorflow#4]
Thanks for your excellent reimplement. 
I would like to know whether you have a pytorch version?

**Comment by PointCloudYC** [comment]
> Thanks for your excellent reimplement. I would like to know whether you have a pytorch version?

Thanks for your attention to the implementation. I do not have a SQN pytorch version using  the randlanet as the backbone. You may use other backbones w. pytorch code, say, CloserLook3D, then write your own code to implement the query module and weakly data preparation scheme.

**Comment by liuxuexun** [comment]
Thank you, I have reimplemented it with randla.

**Comment by ybc-ybc** [comment]
> Thank you, I have reimplemented it with randla.

Hello, can you share the pytorch version of SQN, thanks!

**Comment by liuxuexun** [comment]
> > Thank you, I have reimplemented it with randla.
> 
> Hello, can you share the pytorch version of SQN, thanks!

Hi, you can follow my randla reimplement [here](https://github.com/mellody11/RandLA-Net-Pytorch-New), and modify it to SQN just need a little time.

**Comment by ybc-ybc** [comment]
> > > Thank you, I have reimplemented it with randla.
> > 
> > 
> > Hello, can you share the pytorch version of SQN, thanks!
> 
> Hi, you can follow my randla reimplement [here](https://github.com/mellody11/RandLA-Net-Pytorch-New), and modify it to SQN just need a little time.

Thanks!  Where should I refer to modify it?

**Comment by liuxuexun** [comment]
The modificaton should be simple, you just need to modify the dataset (a few points have label) and the network architecture (add a query network, some MLPs, and remove the randlanet decoder) to suit the SQN weakly supervision setting.

You can refer to the origin repo of [QingyongHu](https://github.com/QingyongHu).

**Comment by ybc-ybc** [comment]
> The modificaton should be simple, you just need to modify the dataset (a few points have label) and the network architecture (add a query network, some MLPs, and remove the randlanet decoder) to suit the SQN weakly supervision setting.
> 
> You can refer to the origin repo of [QingyongHu](https://github.com/QingyongHu).

Thanks! I will try.
