### ISSUE TITLE
关于改进

### ISSUE THREAD

**Issue by liuxuexun** [PointCloudYC/SQN_tensorflow#5]
作者您好，很佩服你的优异的复现性能。

想咨询您几个问题：

1.请问您对网络做了哪方面的改进？
2.除了在S3DIS数据集上是否还在其他数据集上有过测试和性能的提升？

期待您的回复。

**Comment by PointCloudYC** [comment]
Thanks for yr attention to the reimplementation of the SQN! This repo aimed at replicating the paper(which was released several months before the official code),so no improvement was made compared w. the paper. 
Only tested on the S3DIS.

**Comment by liuxuexun** [comment]
ok, thanks for your reply.
